### ISSUE TITLE
`npm install ofe` fails on Node v0.11.13 on Windows 7

### ISSUE THREAD

**Issue by Joncom** [trevnorris/node-ofe#8]
![Screenshot](http://i.imgur.com/2NlcOnK.png)

**Comment by trevnorris** [comment]
Sorry. There's no Windows support for this module. I'll keep this open as a reminder for Windows support.

**Comment by trevnorris** [comment]
Sorry. Not sure what's going on. I'll take a look using latest v0.12.

**Comment by santigimeno** [comment]
For the v8 errors see: https://github.com/trevnorris/node-ofe/pull/9
For the snprintf error: https://github.com/trevnorris/node-ofe/pull/10 should do it

Disclaimer: I haven't been able to test them as I have no access to a windows machine at the moment.

For the gettimeofday error, aparently there's no direct replacement on Windows and should be implemented. Googling a little, people are recomending postgresql implementation: http://git.postgresql.org/gitweb/?p=postgresql.git;a=blob;f=src/port/gettimeofday.c;h=75a91993b74414c0a1c13a2a09ce739cb8aa8a08;hb=HEAD. Don't know if there are any licensing issue though.

**Comment by Joncom** [comment]
[#9](https://github.com/trevnorris/node-ofe/pull/9) does seem to have resolved the v8 errors.
[#10](https://github.com/trevnorris/node-ofe/pull/10) does seem to have resolved the snprintf error.

![Screenshot](http://i.imgur.com/HC6ZFN2.png)

**Comment by Joncom** [comment]
I was able to get the install to work by [removing the dependency on the gettimeofday function](https://github.com/Joncom/node-ofe/commit/ee30117b3add585d7bc1ae0dc52ca37a196f173b).

![Screenshot](http://i.imgur.com/Q7YExLM.png)

Not ideal, but it works for my purposes for now since.

Leaving the issue open because what works for me doesn't necessarily help others.

**Comment by trevnorris** [comment]
The mentioned patches have been merged and 0.3.0 has been published to npm.

@Joncom If that's fine w/ you, consider this resolved?

**Comment by Joncom** [comment]
It seems like `npm install ofe` will continue to fail for (all?) Windows users regardless of Node version. Therefore I'd technically consider this an outstanding issue. However, it's your call and I won't mind either way.

**Comment by trevnorris** [comment]
@Joncom if you want, throw your gist into a PR that `ifdef`s the offending code block.

**Comment by rioki** [comment]
Just rand across ofe; this issue persists with version 0.3.0 and Windows 7.

**Comment by rioki** [comment]
I would say this SO question applies here: http://stackoverflow.com/questions/10905892/equivalent-of-gettimeday-for-windows

If you don't mind, I will provide a patch.

**Comment by rioki** [comment]
If you like, I created pull request #11. Unfortunately this changes the format, but the format now conforms to that of node-inspector's dump files (no ms). That implementation is portable to everything that has a C standard library.

**Comment by trevnorris** [comment]
@rioki I have no special attraction to the current format. Key is to keep names unique.

Also, when you say 0.3.0, do you mean Node.js v0.3.0?

**Comment by rioki** [comment]
Version 0.3.0 of ofe. Sorry I thought that was obvious.

**Comment by trevnorris** [comment]
@rioki You were. I had a mental multitasking fail.

**Comment by trevnorris** [comment]
Can we verify if this has been fixed by the latest 0.4.0 release?

**Comment by Joncom** [comment]
![Screenshot](http://i.imgur.com/BVWfmUK.png)

**Comment by rioki** [comment]
tnx
